//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK.WebScraping.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public int fieldID { get; set; }
        public System.Guid pageID { get; set; }
        public System.DateTime createDate { get; set; }
        public short status { get; set; }
        public string map1 { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Page Page { get; set; }
    }
}
