//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK.WebScraping.Shared.Model

{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Page()
        {
            this.Map = new HashSet<Map>();
        }
    
        public System.Guid pageID { get; set; }
        public System.Guid storeID { get; set; }
        public string url { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> lastReadDate { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> deleteDate { get; set; }
        public short status { get; set; }
        public short mapStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Map> Map { get; set; }
        public virtual Store Store { get; set; }
    }
}
