//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK.WebScraping.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductData
    {
        public System.Guid productID { get; set; }
        public int fieldID { get; set; }
        public Nullable<int> intData { get; set; }
        public string stringData { get; set; }
        public Nullable<System.DateTime> dateTimeData { get; set; }
        public System.DateTime createDate { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual Product Product { get; set; }
    }
}
